In [1]:
from fetch import *
import pandas as pd
import json

In [2]:
db_path = "db"
data = []
data = download_leaderboard_data(db_path)

Current seasonId is 14, total pages: 159
Downloading page 1...
Downloading page 2...
Downloading page 3...
Downloading page 4...
Downloading page 5...
Downloading page 6...
Downloading page 7...
Downloading page 8...
Downloading page 9...
Downloading page 10...
Downloading page 11...
Downloading page 12...
Downloading page 13...
Downloading page 14...
Downloading page 15...
Downloading page 16...
Downloading page 17...
Downloading page 18...
Downloading page 19...
Downloading page 20...
Downloading page 21...
Downloading page 22...
Downloading page 23...
Downloading page 24...
Downloading page 25...
Downloading page 26...
Downloading page 27...
Downloading page 28...
Downloading page 29...
Downloading page 30...
Downloading page 31...
Downloading page 32...
Downloading page 33...
Downloading page 34...
Downloading page 35...
Downloading page 36...
Downloading page 37...
Downloading page 38...
Downloading page 39...
Downloading page 40...
Downloading page 41...
Downloading page 42...
Downloading page 43...
Downloading page 44...
Downloading page 45...
Downloading page 46...
Downloading page 47...
Downloading page 48...
Downloading page 49...
Downloading page 50...
Downloading page 51...
Downloading page 52...
Downloading page 53...
Downloading page 54...
Downloading page 55...
Downloading page 56...
Downloading page 57...
Downloading page 58...
Downloading page 59...
Downloading page 60...
Downloading page 61...
Downloading page 62...
Downloading page 63...
Downloading page 64...
Downloading page 65...
Downloading page 66...
Downloading page 67...
Downloading page 68...
Downloading page 69...
Downloading page 70...
Downloading page 71...
Downloading page 72...
Downloading page 73...
Downloading page 74...
Downloading page 75...
Downloading page 76...
Downloading page 77...
Downloading page 78...
Downloading page 79...
Downloading page 80...
Downloading page 81...
Downloading page 82...
Downloading page 83...
Downloading page 84...
Downloading page 85...
Downloading page 86...
Downloading page 87...
Downloading page 88...
Downloading page 89...
Downloading page 90...
Downloading page 91...
Downloading page 92...
Downloading page 93...
Downloading page 94...
Downloading page 95...
Downloading page 96...
Downloading page 97...
Downloading page 98...
Downloading page 99...
Downloading page 100...
Downloading page 101...
Downloading page 102...
Downloading page 103...
Downloading page 104...
Downloading page 105...
Downloading page 106...
Downloading page 107...
Downloading page 108...
Downloading page 109...
Downloading page 110...
Downloading page 111...
Downloading page 112...
Downloading page 113...
Downloading page 114...
Downloading page 115...
Downloading page 116...
Downloading page 117...
Downloading page 118...
Downloading page 119...
Downloading page 120...
Downloading page 121...
Downloading page 122...
Downloading page 123...
Downloading page 124...
Downloading page 125...
Downloading page 126...
Downloading page 127...
Downloading page 128...
Downloading page 129...
Downloading page 130...
Downloading page 131...
Downloading page 132...
Downloading page 133...
Downloading page 134...
Downloading page 135...
Downloading page 136...
Downloading page 137...
Downloading page 138...
Downloading page 139...
Downloading page 140...
Downloading page 141...
Downloading page 142...
Downloading page 143...
Downloading page 144...
Downloading page 145...
Downloading page 146...
Downloading page 147...
Downloading page 148...
Downloading page 149...
Downloading page 150...
Downloading page 151...
Downloading page 152...
Downloading page 153...
Downloading page 154...
Downloading page 155...
Downloading page 156...
Downloading page 157...
Downloading page 158...
Downloading page 159...
Done downloading. Time taken {} seconds. 260.20427227020264
Done writing to file db

In [3]:
if len(data) == 0:
    with open(db_path, "r") as db:
        data += json.load(db)

df = pd.DataFrame(data)
df.style.hide(axis='index')

In [4]:
queries = [
    "Bugs", "Mighty"
]
view = df.loc[df['accountid'].str.contains("|".join(queries))]
view.style.hide(axis='index')